language: node_js
node_js:
  - 10
  - 8

install:
  - yarn install --frozen-lockfile

script:
  - yarn build
  - yarn test
  - yarn lint

deploy:
  api_key: c6167507-5d07-4c27-b6b6-672d3aeedc55
  provider: script
  skip_cleanup: true
  script:
    - yarn exec semantic-release
  on:
    all_branches: true
    node_js: 10
